### ISSUE TITLE
Please use standard XDG path to store notes

### ISSUE THREAD

**Issue by z0rc** [chipsenkbeil/zsh-notes#1]
It isn't acceptable in 2018, where [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) is more than a decade old, to create dotfiles in `$HOME`. Please use `$XDG_DATA_HOME`.

**Comment by chipsenkbeil** [comment]
Sorry, never noticed this. PRs are welcome here.

**Comment by BachoSeven** [comment]
I've implemented this in a backwards-compatible by checking if `$HOME/.notes` exists, and in case it does not
`${$XDG_DATA_HOME:-$HOME/.local/share}/notes` becomes the base_path as per XDG specifications.
